name: SETUP

#Control when it will run
on:
  push:
    branches: [main]

  #Allow to be run manually
  workflow_dispatch:

env:
  REGISTRY: "registry.digitalocean.com/cybercityregistry"
  IMAGE_NAME: "rabbitmq-setup:latest"

#jobs to execute
jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Remove all old images
        run: if [ ! - z "(doctl registry repository list | grep "$(echo $IMAGE_NAME)")" ]; then doctl registry repository delete-manifest $(echo $IMAGE_NAME) $(doctl registry repository list-tags $(echo $IMAGE_NAME) | grep -o "sha.*") --force; else echo "No repository"; fi

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME)
      
      - name: Deploy script
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -azvr --delete
          path: conf/
          remote_path: ~/rabbitmqsetup
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY}}
          remote_key_pass: ${{ secrets.SSH_PASSPHRASE }}

  deploy:
    runs-on: ubuntu-20.04
    needs: build_and_push

    steps:
      - name: Start Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY}}
          script: |
            cd ~/docker
            docker-compose pull
            docker-compose up -d --force-recreate
